import { steps } from '../src/features/guide/catalog.ts';
import type { Lesson } from '../src/features/guide/lesson/types.ts';
import type { LessonSource } from '../content/guide/types.ts';

// Splits a written lesson into what members read (`guide_steps.lesson`) and the answer key only the
// server sees (`private.guide_checks`). Used by the migration generator and by the tests.

export type AnswerKey = Record<string, { correct: string[]; why: Record<string, string> }>;
export type CompiledLesson = { stepId: string; lesson: Lesson; key: AnswerKey | null };

const stepIds = new Set(steps.map(step => step.id));
const idPattern = /^[a-z0-9]+(-[a-z0-9]+)*$/;
const unique = (ids: string[]) => new Set(ids).size === ids.length;

function problems(source: LessonSource) {
  const found: string[] = [];
  if (!stepIds.has(source.stepId)) found.push('the step is not in catalog.ts');
  if (!/^\d{4}-\d{2}-\d{2}$/.test(source.verified)) found.push('`verified` is not YYYY-MM-DD');
  if (source.claudeCode !== undefined && !/^\d+\.\d+\.\d+$/.test(source.claudeCode)) found.push('`claudeCode` is not a release like 2.1.289');
  if (!source.check) return found;
  const { questions } = source.check;
  if (questions.length < 2 || questions.length > 4) found.push('a check has 2 to 4 questions');
  if (!unique(questions.map(question => question.id))) found.push('question ids repeat');
  for (const question of questions) {
    const right = question.options.filter(option => option.correct).length;
    if (!idPattern.test(question.id)) found.push(`question «${question.id}»: id is not kebab-case`);
    if (question.options.length < 2) found.push(`question ${question.id}: fewer than 2 options`);
    if (!unique(question.options.map(option => option.id))) found.push(`question ${question.id}: option ids repeat`);
    if (question.multiple ? right < 1 : right !== 1) found.push(`question ${question.id}: ${question.multiple ? 'no right option' : 'needs exactly one right option'}`);
    for (const option of question.options) {
      if (!idPattern.test(option.id)) found.push(`question ${question.id}: option «${option.id}» is not kebab-case`);
      if (!option.why.trim()) found.push(`question ${question.id}: option ${option.id} has no explanation`);
    }
  }
  return found;
}

export function compileLesson(source: LessonSource): CompiledLesson {
  const found = problems(source);
  if (found.length) throw new Error(`content/guide ${source.stepId}: ${found.join('; ')}`);
  // Listed field by field, so nothing from the source reaches members by accident.
  const lesson: Lesson = { minutes: source.minutes, outcome: source.outcome, blocks: source.blocks, practice: source.practice };
  if (source.claudeCode) lesson.verified = { date: source.verified, claudeCode: source.claudeCode };
  if (!source.check) return { stepId: source.stepId, lesson, key: null };
  const { questions } = source.check;
  lesson.check = {
    questions: questions.map(question => ({
      id: question.id,
      prompt: question.prompt,
      ...(question.multiple ? { multiple: true } : {}),
      options: question.options.map(option => ({ id: option.id, text: option.text })),
    })),
  };
  const key: AnswerKey = Object.fromEntries(questions.map(question => [question.id, {
    correct: question.options.filter(option => option.correct).map(option => option.id),
    why: Object.fromEntries(question.options.map(option => [option.id, option.why])),
  }]));
  return { stepId: source.stepId, lesson, key };
}

function jsonLiteral(value: unknown) {
  const json = JSON.stringify(value, null, 2);
  let tag = 'json';
  while (json.includes(`$${tag}$`)) tag += '_';
  return `$${tag}$${json}$${tag}$::jsonb`;
}

// The migration that publishes these lessons. Step ids are catalog ids, safe as SQL literals.
export function contentMigration(lessons: CompiledLesson[]) {
  const statements = lessons.flatMap(({ stepId, lesson, key }) => [
    `-- ${stepId}: generated by \`npm run guide:content\` from content/guide/${stepId}.ts. Edit the source, not this file.`,
    `update public.guide_steps set lesson = ${jsonLiteral(lesson)} where step_id = '${stepId}';`,
    key
      ? `insert into private.guide_checks (step_id, key) values ('${stepId}', ${jsonLiteral(key)})\non conflict (step_id) do update set key = excluded.key;`
      : `delete from private.guide_checks where step_id = '${stepId}';`,
    '',
  ]);
  return ['begin;', '', ...statements, 'commit;', ''].join('\n');
}
