import { steps } from '../src/features/guide/catalog.ts';
import type { LibraryBodyRow, LibraryItemRow } from '../src/features/library/types.ts';
import type { LibrarySource } from '../content/library/types.ts';

// Splits the written library into its rows: titles every member reads (`library_items`) and bodies
// that open with a passed step (`library_bodies`). Used by the migration generator and by the tests.

export type CompiledMaterial = { item: LibraryItemRow; body: LibraryBodyRow };

const stepOrder = new Map(steps.map((step, index) => [step.id, index]));
const idPattern = /^[a-z0-9]+(-[a-z0-9]+)*$/;

function problems(sources: LibrarySource[]) {
  const found: string[] = [];
  const ids = new Set<string>();
  let previous = -1;
  for (const source of sources) {
    const at = `content/library ${source.id}`;
    if (!idPattern.test(source.id)) found.push(`${at}: id is not kebab-case`);
    if (ids.has(source.id)) found.push(`${at}: the id repeats`);
    ids.add(source.id);
    const order = stepOrder.get(source.stepId);
    if (order === undefined) found.push(`${at}: the step is not in catalog.ts`);
    else if (order < previous) found.push(`${at}: out of route order`);
    else previous = order;
    if (!source.title.trim() || !source.summary.trim() || !source.body.trim()) found.push(`${at}: an empty title, summary or body`);
    if (source.kind === 'prompt' ? source.file !== undefined : !source.file) found.push(`${at}: a prompt has no file, other kinds need one`);
  }
  return found;
}

export function compileLibrary(sources: LibrarySource[]): CompiledMaterial[] {
  const found = problems(sources);
  if (found.length) throw new Error(found.join('; '));
  // Listed field by field, so nothing else from the source reaches members.
  return sources.map((source, position) => ({
    item: { id: source.id, step_id: source.stepId, position, kind: source.kind, title: source.title, summary: source.summary },
    body: { item_id: source.id, file: source.file ?? null, body: source.body },
  }));
}

function text(value: string | null) {
  if (value === null) return 'null';
  let tag = 'txt';
  while (value.includes(`$${tag}$`)) tag += '_';
  return `$${tag}$${value}$${tag}$`;
}

// The migration that makes the database's library exactly the sources: upserts every material,
// removes the ones no longer written. Ids and step ids are checked kebab-case, safe as literals.
export function libraryMigration(materials: CompiledMaterial[]) {
  const ids = materials.map(({ item }) => `'${item.id}'`).join(', ');
  return [
    'begin;',
    '',
    '-- Generated by `npm run library:content` from content/library/. Edit the sources, not this file.',
    `delete from public.library_items where id not in (${ids});`,
    '',
    'insert into public.library_items (id, step_id, position, kind, title, summary) values',
    materials.map(({ item }) => `  ('${item.id}', '${item.step_id}', ${item.position}, '${item.kind}', ${text(item.title)}, ${text(item.summary)})`).join(',\n'),
    'on conflict (id) do update set step_id = excluded.step_id, position = excluded.position, kind = excluded.kind, title = excluded.title, summary = excluded.summary;',
    '',
    'insert into public.library_bodies (item_id, file, body) values',
    materials.map(({ body }) => `  ('${body.item_id}', ${text(body.file)}, ${text(body.body)})`).join(',\n'),
    'on conflict (item_id) do update set file = excluded.file, body = excluded.body;',
    '',
    'commit;',
    '',
  ].join('\n');
}
