begin;

-- hooks: generated by `npm run guide:content` from content/guide/hooks.ts. Edit the source, not this file.
update public.guide_steps set lesson = $json${
  "minutes": 14,
  "outcome": "Вы превращаете правила, которые агент обязан соблюдать, в хуки — команды, которые Claude Code сам запускает в нужный момент.",
  "blocks": [
    {
      "type": "text",
      "text": "CLAUDE.md — совет, и агент может от него отступить (шаг 2.3). Хук — команда, которую Claude Code запускает сам на определённом событии: перед действием агента, после него, в конце хода. Хук выполнится всегда, что бы агент ни решил."
    },
    {
      "type": "diagram",
      "name": "hook-events",
      "caption": "Хуки срабатывают на событиях сессии. Самые полезные — до и после каждого инструмента и в конце хода."
    },
    {
      "type": "heading",
      "text": "Хук в настройках"
    },
    {
      "type": "code",
      "file": ".claude/settings.json",
      "code": "{\n  \"hooks\": {\n    \"PostToolUse\": [\n      {\n        \"matcher\": \"Edit|Write\",\n        \"hooks\": [\n          {\n            \"type\": \"command\",\n            \"command\": \"node \\\"$CLAUDE_PROJECT_DIR/.claude/hooks/typecheck.mjs\\\"\"\n          }\n        ]\n      }\n    ]\n  }\n}",
      "caption": "После каждой правки файла Claude Code запустит проверку типов. `matcher` выбирает инструменты, на которые реагирует хук."
    },
    {
      "type": "heading",
      "text": "Как хук говорит «нет»"
    },
    {
      "type": "list",
      "items": [
        "Хук получает на вход JSON с описанием события: какой инструмент и с какими параметрами.",
        "**Код выхода 0** — всё в порядке, работа идёт дальше.",
        "**Код выхода 2** — действие блокируется, а текст из stderr уходит агенту: он видит причину и исправляется сам."
      ]
    },
    {
      "type": "code",
      "file": ".claude/hooks/typecheck.mjs",
      "code": "import { spawnSync } from 'node:child_process';\n\nlet input = '';\nfor await (const chunk of process.stdin) input += chunk;\nconst { file_path } = JSON.parse(input).tool_input;\nif (!/\\.tsx?$/.test(file_path)) process.exit(0);\n\nconst { status, stdout } = spawnSync('npx tsc --noEmit', { shell: true, encoding: 'utf8' });\nif (status !== 0) {\n  process.stderr.write(`Ошибки типов после правки ${file_path}:\\n${stdout}`);\n  process.exit(2);\n}",
      "caption": "Почти такой же хук работает в проекте, где пишется этот курс: агент не может оставить правку с ошибками типов."
    },
    {
      "type": "session",
      "title": "~/projects/shop",
      "summary": "Симуляция сеанса: агент добавляет поле в тип заказа. Хук после правки запускает проверку типов и возвращает агенту две ошибки в другом файле. Агент сам исправляет использования, и следующая проверка проходит.",
      "lines": [
        {
          "kind": "prompt",
          "text": "Добавь поле discount в тип Order.",
          "typed": true
        },
        {
          "kind": "edit",
          "text": "src/types/order.ts",
          "diff": "+1"
        },
        {
          "kind": "meta",
          "text": "PostToolUse → typecheck: 2 ошибки в cart.ts"
        },
        {
          "kind": "info",
          "text": "Хук вернул ошибки: поле нужно и в createOrder()"
        },
        {
          "kind": "edit",
          "text": "src/cart/cart.ts",
          "diff": "+2"
        },
        {
          "kind": "meta",
          "text": "PostToolUse → typecheck: ошибок нет"
        },
        {
          "kind": "done",
          "text": "Готово: тип и все его использования согласованы."
        }
      ]
    },
    {
      "type": "heading",
      "text": "Что поручить хукам"
    },
    {
      "type": "list",
      "items": [
        "**PostToolUse**: форматтер, линтер или проверка типов после правки.",
        "**PreToolUse**: запрет правки миграций, сгенерированных файлов, продакшен-конфигов.",
        "**Stop**: не дать агенту закончить ход, пока не прошли тесты.",
        "**SessionStart**: подгрузить в контекст свежие сведения, например задачи из трекера."
      ]
    },
    {
      "type": "text",
      "text": "Посмотреть настроенные хуки можно командой `/hooks`. Хуки живут в тех же файлах настроек, что и правила доступа: личных, проектных и локальных."
    },
    {
      "type": "callout",
      "tone": "trap",
      "title": "Хук — это код с вашими правами",
      "text": "Хук выполняет любую команду от вашего имени. Не копируйте чужие хуки не читая и проверяйте изменения в `.claude/settings.json` на ревью так же внимательно, как код."
    },
    {
      "type": "callout",
      "tone": "tip",
      "title": "Совет и закон вместе",
      "text": "Правило в CLAUDE.md объясняет, почему. Хук гарантирует, что. Лучше всего вместе: агент понимает смысл, а хук страхует, когда он забудет."
    }
  ],
  "practice": {
    "task": "Выберите правило, которое агент у вас нарушал: форматирование, запрет правки какого-то файла, обязательные тесты. Сделайте из него хук в `.claude/settings.json` проекта и проверьте, что он срабатывает.",
    "done": [
      "хук описан в `.claude/settings.json` и закоммичен;",
      "вы видели, как хук остановил агента или вернул ему ошибку;",
      "агент исправился сам, по тексту из хука."
    ]
  },
  "check": {
    "questions": [
      {
        "id": "always-format",
        "prompt": "Агент иногда забывает запустить форматтер после правки. Как сделать, чтобы это происходило всегда?",
        "options": [
          {
            "id": "post-hook",
            "text": "Хук `PostToolUse` на `Edit|Write`, который запускает форматтер."
          },
          {
            "id": "claude-md",
            "text": "Строка в CLAUDE.md: «всегда запускай форматтер»."
          },
          {
            "id": "remind",
            "text": "Напоминать в каждом запросе."
          }
        ]
      },
      {
        "id": "exit-code",
        "prompt": "Ваш хук `PreToolUse` нашёл запрещённую правку. Как остановить агента и объяснить ему причину?",
        "options": [
          {
            "id": "exit-2",
            "text": "Выйти с кодом 2 и написать причину в stderr."
          },
          {
            "id": "exit-0",
            "text": "Выйти с кодом 0 и написать причину в stdout."
          },
          {
            "id": "crash",
            "text": "Упасть без сообщения."
          }
        ]
      },
      {
        "id": "which-event",
        "prompt": "Нужно, чтобы агент не мог закончить ход, пока не пройдут тесты. На какое событие повесить хук?",
        "options": [
          {
            "id": "stop",
            "text": "`Stop`"
          },
          {
            "id": "session-start",
            "text": "`SessionStart`"
          },
          {
            "id": "prompt-submit",
            "text": "`UserPromptSubmit`"
          }
        ]
      }
    ]
  }
}$json$::jsonb where step_id = 'hooks';
insert into private.guide_checks (step_id, key) values ('hooks', $json${
  "always-format": {
    "correct": [
      "post-hook"
    ],
    "why": {
      "post-hook": "Да. Хук выполняется после каждой правки, что бы агент ни решил.",
      "claude-md": "Это совет: агент может забыть, особенно в длинной сессии.",
      "remind": "Утомительно и ненадёжно. Хук делает это сам."
    }
  },
  "exit-code": {
    "correct": [
      "exit-2"
    ],
    "why": {
      "exit-2": "Да. Действие блокируется, а текст причины получает агент.",
      "exit-0": "Код 0 значит «всё в порядке»: действие выполнится.",
      "crash": "Агент не узнает, что не так и как исправиться."
    }
  },
  "which-event": {
    "correct": [
      "stop"
    ],
    "why": {
      "stop": "Да. Хук на `Stop` срабатывает, когда агент хочет закончить, и может вернуть его к работе.",
      "session-start": "Это начало сессии — проверять там ещё нечего.",
      "prompt-submit": "Это момент, когда вы отправляете запрос, а не когда агент заканчивает."
    }
  }
}$json$::jsonb)
on conflict (step_id) do update set key = excluded.key;

-- commands-skills: generated by `npm run guide:content` from content/guide/commands-skills.ts. Edit the source, not this file.
update public.guide_steps set lesson = $json${
  "minutes": 13,
  "outcome": "Вы упаковываете повторяющуюся работу в навык (skill) — инструкцию, которую агент вызывает по вашей команде или сам, когда она нужна.",
  "blocks": [
    {
      "type": "text",
      "text": "Если вы в третий раз объясняете агенту одну и ту же процедуру — как выпускать релиз, как проверять перед коммитом, как разбирать баг из поддержки, — пора сделать навык. Это Markdown-файл с инструкцией, который становится командой `/имя`."
    },
    {
      "type": "code",
      "file": ".claude/skills/verify/SKILL.md",
      "code": "---\nname: verify\ndescription: Проверки проекта перед отчётом о готовности — линтер, сборка, тесты. Используй перед тем, как сказать «готово».\n---\n\nЗапусти по порядку, остановись на первой ошибке и исправь её:\n\n1. `npm run lint` — 0 ошибок.\n2. `npm run build` — вместе с проверкой типов.\n3. `npm test` — только затронутые области.",
      "caption": "Такой навык есть в проекте, где пишется этот курс. По `description` агент решает, когда вызвать навык сам; вы вызываете его командой `/verify`."
    },
    {
      "type": "heading",
      "text": "Как устроен навык"
    },
    {
      "type": "list",
      "items": [
        "**Где лежит**: `.claude/skills/<имя>/SKILL.md` — навык проекта, общий для команды; `~/.claude/skills/<имя>/` — личный.",
        "**`name` и `description`** в шапке. По описанию агент решает, когда навык пригодится, поэтому пишите в нём, когда его использовать.",
        "**`disable-model-invocation: true`** — навык вызываете только вы, командой. Подходит для действий с последствиями, например деплоя.",
        "**Аргументы**: в `/fix-issue 482` номер задачи попадёт в текст навыка на место `$ARGUMENTS`."
      ]
    },
    {
      "type": "session",
      "title": "~/projects/shop",
      "summary": "Симуляция сеанса: разработчик вызывает навык fix-issue с номером задачи. Агент читает задачу, по шагам навыка воспроизводит ошибку тестом, исправляет код и запускает навык verify с проверками проекта.",
      "lines": [
        {
          "kind": "prompt",
          "text": "/fix-issue 482",
          "typed": true
        },
        {
          "kind": "info",
          "text": "Навык fix-issue: читаю задачу 482 через gh issue view"
        },
        {
          "kind": "info",
          "text": "По шагам навыка: тест → исправление → проверки"
        },
        {
          "kind": "edit",
          "text": "tests/cart/rounding.spec.ts",
          "diff": "+14"
        },
        {
          "kind": "edit",
          "text": "src/cart/total.ts",
          "diff": "+2 −1"
        },
        {
          "kind": "pass",
          "text": "/verify — линтер, сборка, тесты пройдены"
        },
        {
          "kind": "done",
          "text": "Задача 482 исправлена по процедуре команды."
        }
      ]
    },
    {
      "type": "heading",
      "text": "Навык, CLAUDE.md или хук?"
    },
    {
      "type": "list",
      "items": [
        "**CLAUDE.md** — то, что агент должен знать всегда: команды, соглашения.",
        "**Навык** — процедура, которая нужна иногда: загружается, только когда вызвана, и не занимает окно зря.",
        "**Хук** — то, что должно происходить всегда и без участия агента (шаг 5.1)."
      ]
    },
    {
      "type": "callout",
      "tone": "trap",
      "title": "Описание решает",
      "text": "Агент вызывает навык сам, только если описание подходит к задаче. «Полезные команды» ему ничего не скажут, а «Используй перед отчётом о готовности» — скажет."
    },
    {
      "type": "callout",
      "tone": "tip",
      "title": "Старые команды тоже работают",
      "text": "Файлы в `.claude/commands/` по-прежнему работают как команды. Для новых процедур документация советует навыки: возможностей у них больше."
    }
  ],
  "practice": {
    "task": "Найдите процедуру, которую вы объясняли агенту больше двух раз. Оформите её навыком в `.claude/skills/` с понятным `description` и вызовите командой. Затем дайте задачу, где навык нужен, и посмотрите, вызовет ли агент его сам.",
    "done": [
      "навык лежит в `.claude/skills/<имя>/SKILL.md` и закоммичен;",
      "вы вызвали его командой `/имя`;",
      "в подходящей задаче агент сам воспользовался навыком."
    ]
  },
  "check": {
    "questions": [
      {
        "id": "release-procedure",
        "prompt": "Процедура выпуска релиза нужна раз в неделю и состоит из восьми шагов. Где её хранить?",
        "options": [
          {
            "id": "skill",
            "text": "В навыке `.claude/skills/release/SKILL.md`."
          },
          {
            "id": "claude-md",
            "text": "В CLAUDE.md."
          },
          {
            "id": "hook",
            "text": "В хуке."
          }
        ]
      },
      {
        "id": "never-called",
        "prompt": "Агент никогда сам не вызывает ваш навык проверок. Что поправить первым?",
        "options": [
          {
            "id": "description",
            "text": "Описание: написать, когда его использовать, например «перед отчётом о готовности»."
          },
          {
            "id": "name",
            "text": "Сократить имя навыка."
          },
          {
            "id": "caps",
            "text": "Добавить в текст навыка «ВСЕГДА ВЫЗЫВАЙ МЕНЯ»."
          }
        ]
      },
      {
        "id": "deploy-skill",
        "prompt": "Навык `deploy` выкладывает код в продакшен. Как не дать агенту запустить его самому?",
        "options": [
          {
            "id": "disable",
            "text": "`disable-model-invocation: true` в шапке навыка."
          },
          {
            "id": "no-description",
            "text": "Не писать description."
          },
          {
            "id": "trust",
            "text": "Ничего: агент не станет деплоить без спроса."
          }
        ]
      }
    ]
  }
}$json$::jsonb where step_id = 'commands-skills';
insert into private.guide_checks (step_id, key) values ('commands-skills', $json${
  "release-procedure": {
    "correct": [
      "skill"
    ],
    "why": {
      "skill": "Да. Навык загружается, только когда нужен, и вызывается одной командой.",
      "claude-md": "Восемь шагов будут занимать окно в каждой сессии, хотя нужны раз в неделю.",
      "hook": "Хук срабатывает на событиях сессии сам. Релиз — осознанное действие, его запускают по команде."
    }
  },
  "never-called": {
    "correct": [
      "description"
    ],
    "why": {
      "description": "Да. По описанию агент решает, нужен ли навык.",
      "name": "Имя важно для команды, но решение агент принимает по описанию.",
      "caps": "Текст навыка агент видит, только когда навык уже вызван."
    }
  },
  "deploy-skill": {
    "correct": [
      "disable"
    ],
    "why": {
      "disable": "Да. Такой навык вызываете только вы, командой `/deploy`.",
      "no-description": "Ненадёжно — да и описание нужно, чтобы вы сами помнили, что делает навык.",
      "trust": "Для действий с последствиями нужен запрет, а не надежда."
    }
  }
}$json$::jsonb)
on conflict (step_id) do update set key = excluded.key;

-- mcp: generated by `npm run guide:content` from content/guide/mcp.ts. Edit the source, not this file.
update public.guide_steps set lesson = $json${
  "minutes": 13,
  "outcome": "Вы подключаете агенту внешние инструменты через MCP — трекер, базу, документацию — с подходящей областью действия и под контролем прав.",
  "blocks": [
    {
      "type": "text",
      "text": "MCP (Model Context Protocol) — способ дать агенту инструменты за пределами терминала: задачи из трекера, данные из базы, макеты, документацию. Сервер MCP описывает свои инструменты, а Claude Code вызывает их как собственные."
    },
    {
      "type": "command",
      "code": "claude mcp add --transport http tracker https://mcp.example.com/mcp",
      "caption": "Подключение удалённого сервера по HTTP. Локальный подключается через `--transport stdio` и команду запуска после `--`."
    },
    {
      "type": "heading",
      "text": "Где хранить подключение"
    },
    {
      "type": "list",
      "items": [
        "**local** (по умолчанию) — только у вас и только в этом проекте.",
        "**project** — в файле `.mcp.json` в корне репозитория: подключение получает вся команда.",
        "**user** — у вас во всех проектах."
      ]
    },
    {
      "type": "code",
      "file": ".mcp.json",
      "code": "{\n  \"mcpServers\": {\n    \"db\": {\n      \"type\": \"stdio\",\n      \"command\": \"npx\",\n      \"args\": [\"-y\", \"@example/postgres-mcp\"],\n      \"env\": { \"DATABASE_URL\": \"${READONLY_DATABASE_URL}\" }\n    }\n  }\n}",
      "caption": "Строка подключения берётся из переменной окружения и не лежит в файле, поэтому его можно коммитить. И доступ — только на чтение: агенту редко нужна запись в базу."
    },
    {
      "type": "text",
      "text": "Команда `/mcp` показывает подключённые серверы и их состояние; там же проходит вход в сервисы, которым он нужен."
    },
    {
      "type": "heading",
      "text": "Права на инструменты MCP"
    },
    {
      "type": "text",
      "text": "Инструменты MCP подчиняются тем же правилам доступа, что и всё остальное (шаг 1.2). Их имена выглядят так: `mcp__<сервер>__<инструмент>`."
    },
    {
      "type": "code",
      "file": ".claude/settings.json",
      "code": "{\n  \"permissions\": {\n    \"allow\": [\"mcp__tracker__get_issue\"],\n    \"deny\": [\"mcp__tracker__delete_issue\"]\n  }\n}",
      "caption": "Читать задачи — без вопросов, удалять — никогда."
    },
    {
      "type": "session",
      "title": "~/projects/shop",
      "summary": "Симуляция сеанса: агент через MCP-сервер трекера читает задачу SHOP-214, находит связанный код и по просьбе разработчика составляет план. Задачу не пришлось копировать вручную.",
      "lines": [
        {
          "kind": "prompt",
          "text": "Возьми задачу SHOP-214 из трекера и оцени, что нужно поменять.",
          "typed": true
        },
        {
          "kind": "info",
          "text": "mcp__tracker__get_issue SHOP-214: «Скидка не действует на доставку»"
        },
        {
          "kind": "info",
          "text": "Связанный код: src/cart/total.ts, src/shipping/price.ts"
        },
        {
          "kind": "prompt",
          "text": "Составь план, правки после согласования.",
          "typed": true
        },
        {
          "kind": "info",
          "text": "План: учесть доставку в total(), тест на заказ с доставкой"
        },
        {
          "kind": "done",
          "text": "План готов. Задача прочитана из трекера без копирования."
        }
      ]
    },
    {
      "type": "callout",
      "tone": "trap",
      "title": "Сервер MCP — чужой код и чужие данные",
      "text": "Подключайте только серверы, которым доверяете: они работают с вашими правами и возвращают агенту текст, в котором могут оказаться инструкции. Давайте минимальные права — только чтение там, где запись не нужна."
    },
    {
      "type": "callout",
      "tone": "tip",
      "title": "Не держите лишнее",
      "text": "Каждый сервер добавляет инструменты, которые агенту приходится различать. Подключайте то, чем пользуетесь, и отключайте лишнее в `/mcp`."
    }
  ],
  "practice": {
    "task": "Подключите сервер MCP к сервису, с которым работаете каждый день: трекеру, базе в режиме чтения, документации. Выберите область действия, задайте правила allow и deny для его инструментов и дайте агенту задачу, где он пригодится.",
    "done": [
      "сервер виден в `/mcp` как подключённый;",
      "для его инструментов есть правила в настройках;",
      "агент получил данные из сервиса сам, без вашего копирования."
    ]
  },
  "check": {
    "questions": [
      {
        "id": "team-scope",
        "prompt": "Вся команда должна пользоваться одним MCP-сервером трекера задач. Какую область выбрать?",
        "options": [
          {
            "id": "project",
            "text": "`--scope project`: подключение ляжет в `.mcp.json` и попадёт в репозиторий."
          },
          {
            "id": "local",
            "text": "По умолчанию, `local`."
          },
          {
            "id": "user",
            "text": "`--scope user`."
          }
        ]
      },
      {
        "id": "secret-in-config",
        "prompt": "Серверу нужна строка подключения к базе с паролем. Как указать её в `.mcp.json`, который коммитится?",
        "options": [
          {
            "id": "env",
            "text": "Через переменную окружения: `${READONLY_DATABASE_URL}`."
          },
          {
            "id": "inline",
            "text": "Вписать строку прямо в файл."
          },
          {
            "id": "readme",
            "text": "Положить строку в README рядом."
          }
        ]
      },
      {
        "id": "deny-mcp",
        "prompt": "Как запретить агенту удалять задачи через MCP-сервер `tracker`?",
        "options": [
          {
            "id": "deny",
            "text": "Правило `deny` на `mcp__tracker__delete_issue`."
          },
          {
            "id": "ask",
            "text": "Попросить агента в запросе ничего не удалять."
          },
          {
            "id": "remove",
            "text": "Отключить сервер целиком."
          }
        ]
      }
    ]
  }
}$json$::jsonb where step_id = 'mcp';
insert into private.guide_checks (step_id, key) values ('mcp', $json${
  "team-scope": {
    "correct": [
      "project"
    ],
    "why": {
      "project": "Да. Коллеги получат его вместе с кодом.",
      "local": "Так сервер увидите только вы и только в этом проекте.",
      "user": "Это ваш личный сервер для всех проектов — коллеги его не получат."
    }
  },
  "secret-in-config": {
    "correct": [
      "env"
    ],
    "why": {
      "env": "Да. В файле остаётся имя переменной, а сам секрет — у каждого в окружении.",
      "inline": "Пароль окажется в репозитории и в истории git.",
      "readme": "Ещё хуже: секрет в открытом виде для всех."
    }
  },
  "deny-mcp": {
    "correct": [
      "deny"
    ],
    "why": {
      "deny": "Да. Инструменты MCP подчиняются тем же правилам доступа.",
      "ask": "Это совет, а не запрет.",
      "remove": "Слишком грубо: остальные инструменты сервера полезны."
    }
  }
}$json$::jsonb)
on conflict (step_id) do update set key = excluded.key;

-- git-flow: generated by `npm run guide:content` from content/guide/git-flow.ts. Edit the source, not this file.
update public.guide_steps set lesson = $json${
  "minutes": 12,
  "outcome": "Вы поручаете агенту ветки, коммиты и PR, а решения, которые нельзя откатить, оставляете себе.",
  "blocks": [
    {
      "type": "text",
      "text": "Рутину git агент делает отлично: создаёт ветку, пишет понятное сообщение коммита, открывает PR с описанием. Ваша часть — всё, что выходит за пределы вашей машины: пуш, слияние, публикация."
    },
    {
      "type": "heading",
      "text": "Что отдать агенту"
    },
    {
      "type": "list",
      "items": [
        "**Ветку под задачу**: «создай ветку fix/promo-rounding от main».",
        "**Коммиты по шагам**: агент пишет сообщение по diff. Формат, принятый в команде, запишите в CLAUDE.md.",
        "**PR**: «создай PR» — агент воспользуется `gh pr create` (для GitLab — `glab`) и опишет изменения.",
        "**Разбор конфликтов** при обновлении ветки — с вашей проверкой результата."
      ]
    },
    {
      "type": "heading",
      "text": "Что оставить себе"
    },
    {
      "type": "list",
      "items": [
        "**Пуш и слияние в main** — если сомневаетесь, запретите правилом `deny` на `Bash(git push *)` (шаг 1.2).",
        "**Переписывание истории**: `git push --force`, `rebase` общих веток.",
        "**Финальное ревью** перед слиянием (шаг 4.1)."
      ]
    },
    {
      "type": "code",
      "file": "CLAUDE.md",
      "code": "## Git\n- Ветки: `fix/…`, `feat/…` от `main`\n- Коммиты: `тип: что сделано`, по-английски, в повелительном наклонении\n- PR: проблема, решение, как проверено; скриншоты для изменений UI\n- Не пушить и не сливать — это делает человек",
      "caption": "Эти соглашения агент повторит в каждом коммите и PR. Последнюю строку подкрепите правилом `deny`."
    },
    {
      "type": "session",
      "title": "~/projects/shop",
      "summary": "Симуляция сеанса: агент создаёт ветку, исправляет округление, прогоняет тесты и делает коммит в формате команды. Пуш он оставляет разработчику; после пуша агент открывает PR через gh pr create.",
      "lines": [
        {
          "kind": "prompt",
          "text": "Ветка fix/promo-rounding, исправь округление, коммит в нашем формате.",
          "typed": true
        },
        {
          "kind": "info",
          "text": "git switch -c fix/promo-rounding"
        },
        {
          "kind": "edit",
          "text": "src/cart/total.ts",
          "diff": "+2 −1"
        },
        {
          "kind": "pass",
          "text": "npm test — пройдено"
        },
        {
          "kind": "info",
          "text": "git commit -m \"fix: round promo discounts to kopecks\""
        },
        {
          "kind": "meta",
          "text": "git push — по правилам проекта это делаете вы"
        },
        {
          "kind": "prompt",
          "text": "Запушил. Открой PR.",
          "typed": true
        },
        {
          "kind": "info",
          "text": "gh pr create --title \"fix: round promo discounts to kopecks\""
        },
        {
          "kind": "done",
          "text": "PR открыт: что изменено, почему и как проверено."
        }
      ]
    },
    {
      "type": "callout",
      "tone": "trap",
      "title": "Сообщение пишет агент, смысл проверяете вы",
      "text": "Агент гладко опишет diff, даже если изменение спорное. Читайте описание PR как отчёт: совпадает ли «что и почему» с тем, что вы просили."
    },
    {
      "type": "callout",
      "tone": "tip",
      "title": "Две задачи сразу",
      "text": "Хотите, чтобы агент вёл две задачи параллельно и они не мешали друг другу? Для этого есть worktrees — отдельные рабочие копии на разных ветках. Подробно — на этапе 6."
    }
  ],
  "practice": {
    "task": "Проведите одну задачу через полный git-цикл с агентом: ветка, коммиты по шагам, PR с описанием. Пуш и слияние сделайте сами. Если соглашений о ветках и коммитах нет в CLAUDE.md, допишите их.",
    "done": [
      "ветку, коммиты и PR создал агент в принятом у вас формате;",
      "пуш и слияние сделали вы;",
      "соглашения по git записаны в CLAUDE.md."
    ]
  },
  "check": {
    "questions": [
      {
        "id": "keep-yourself",
        "prompt": "Что разумнее оставить себе, а не агенту?",
        "multiple": true,
        "options": [
          {
            "id": "push-merge",
            "text": "Пуш и слияние в main."
          },
          {
            "id": "rewrite",
            "text": "Переписывание истории общих веток."
          },
          {
            "id": "messages",
            "text": "Сообщения коммитов."
          },
          {
            "id": "branches",
            "text": "Создание веток под задачу."
          }
        ]
      },
      {
        "id": "commit-format",
        "prompt": "Агент пишет сообщения коммитов не в том формате, что принят в команде. Как исправить надолго?",
        "options": [
          {
            "id": "claude-md",
            "text": "Записать формат в CLAUDE.md."
          },
          {
            "id": "each-time",
            "text": "Поправлять каждый раз."
          },
          {
            "id": "by-hand",
            "text": "Писать коммиты самому."
          }
        ]
      },
      {
        "id": "pr-description",
        "prompt": "Агент открыл PR с гладким описанием. Что важно проверить?",
        "options": [
          {
            "id": "matches",
            "text": "Совпадает ли описанное «что и почему» с вашей задачей и с самим diff."
          },
          {
            "id": "grammar",
            "text": "Грамотность текста."
          },
          {
            "id": "nothing",
            "text": "Ничего: описание составлено по diff."
          }
        ]
      }
    ]
  }
}$json$::jsonb where step_id = 'git-flow';
insert into private.guide_checks (step_id, key) values ('git-flow', $json${
  "keep-yourself": {
    "correct": [
      "push-merge",
      "rewrite"
    ],
    "why": {
      "push-merge": "Да. Это выходит за пределы вашей машины и затрагивает всех.",
      "rewrite": "Да. Такую ошибку трудно откатить, а пострадают коллеги.",
      "messages": "Это как раз хорошая работа для агента: он пишет их по diff в вашем формате.",
      "branches": "Рутинная и безопасная операция — её можно отдать агенту."
    }
  },
  "commit-format": {
    "correct": [
      "claude-md"
    ],
    "why": {
      "claude-md": "Да. Агент прочитает его в каждой сессии.",
      "each-time": "Утомительно, и ошибка будет повторяться.",
      "by-hand": "Можно, но незачем: с правилом в CLAUDE.md агент справится."
    }
  },
  "pr-description": {
    "correct": [
      "matches"
    ],
    "why": {
      "matches": "Да. Описание пишет автор изменений — проверяйте его так же, как код.",
      "grammar": "Это вторично: важно, правдиво ли описание.",
      "nothing": "По diff можно гладко описать и ошибочное изменение."
    }
  }
}$json$::jsonb)
on conflict (step_id) do update set key = excluded.key;

-- agent-ci: generated by `npm run guide:content` from content/guide/agent-ci.ts. Edit the source, not this file.
update public.guide_steps set lesson = $json${
  "minutes": 13,
  "outcome": "Вы запускаете агента в CI — ответы на `@claude`, автоматическое ревью, безголовые прогоны `claude -p` — с секретами и правами под контролем.",
  "blocks": [
    {
      "type": "text",
      "text": "Агент не обязан жить только в вашем терминале. В CI он отвечает на упоминания в задачах и PR, ревьюит каждый PR и выполняет рутину по расписанию — тот же Claude Code, только без интерактива."
    },
    {
      "type": "heading",
      "text": "GitHub Actions за одну команду"
    },
    {
      "type": "command",
      "code": "/install-github-app",
      "caption": "Запустите в Claude Code: команда установит приложение GitHub, добавит секрет и подготовит файл workflow."
    },
    {
      "type": "code",
      "file": ".github/workflows/claude.yml",
      "code": "name: Claude Code\non:\n  issue_comment:\n    types: [created]\njobs:\n  claude:\n    if: contains(github.event.comment.body, '@claude')\n    runs-on: ubuntu-latest\n    permissions:\n      contents: write\n      pull-requests: write\n      issues: write\n      id-token: write\n    steps:\n      - uses: actions/checkout@v6\n      - uses: anthropics/claude-code-action@v1\n        with:\n          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}",
      "caption": "Теперь комментарий «@claude поправь опечатку в README» в задаче или PR запустит агента. Ключ хранится в секретах репозитория, а не в файле."
    },
    {
      "type": "heading",
      "text": "Два режима"
    },
    {
      "type": "list",
      "items": [
        "**По упоминанию**: агент отвечает на `@claude` в комментариях — так работает workflow без входа `prompt`.",
        "**Автоматический**: с входом `prompt` агент выполняет заданную работу на событие или по расписанию — например, ревью каждого PR."
      ]
    },
    {
      "type": "heading",
      "text": "Безголовый запуск"
    },
    {
      "type": "text",
      "text": "В любом CI, не только в GitHub, работает `claude -p`: запрос без интерактива, результат — в stdout. Для GitLab в документации есть готовый пример."
    },
    {
      "type": "command",
      "code": "claude -p \"Найди в изменениях ветки места без тестов\" --output-format json --allowedTools \"Read,Grep,Glob\" --max-turns 10",
      "caption": "`--allowedTools` разрешает только чтение, `--max-turns` ограничивает число ходов, а JSON удобно разбирать скриптом."
    },
    {
      "type": "session",
      "title": "ci · feature/promo",
      "summary": "Симуляция прогона в CI: claude -p читает изменения ветки, находит место без тестов и возвращает результат в JSON для следующего шага пайплайна.",
      "lines": [
        {
          "kind": "command",
          "text": "claude -p \"Найди места без тестов\" --output-format json",
          "typed": true
        },
        {
          "kind": "info",
          "text": "Читаю изменения ветки feature/promo: 6 файлов"
        },
        {
          "kind": "info",
          "text": "Без тестов: src/cart/promo.ts — ветка с просроченным кодом"
        },
        {
          "kind": "done",
          "text": "{\"result\": \"Без тестов: 1 место\", \"session_id\": \"…\"}"
        }
      ]
    },
    {
      "type": "callout",
      "tone": "trap",
      "title": "В CI агент работает без вас",
      "text": "Никто не нажмёт Esc и не отклонит правку. Давайте минимальные права: инструменты — через `--allowedTools`, права workflow — только нужные, ключи — только в секретах. Изменения агента из CI всё равно проходят ревью перед слиянием."
    },
    {
      "type": "callout",
      "tone": "tip",
      "title": "Начните с чтения",
      "text": "Первый сценарий в CI — ревью и поиск проблем, где агент только читает и комментирует. Задачи с правками добавляйте, когда увидите, как он себя ведёт."
    }
  ],
  "practice": {
    "task": "Подключите агента к репозиторию через `/install-github-app` или вручную. В комментарии к тестовой задаче попросите `@claude` сделать мелкую правку и откройте PR, который он создаст. Проверьте, что ключ лежит в секретах, а права workflow минимальны.",
    "done": [
      "агент ответил на `@claude` и сделал PR;",
      "ключ API хранится в секретах репозитория;",
      "права workflow ограничены нужным."
    ]
  },
  "check": {
    "questions": [
      {
        "id": "api-key",
        "prompt": "Где хранить ключ API для workflow с агентом?",
        "options": [
          {
            "id": "secrets",
            "text": "В секретах репозитория: `${{ secrets.ANTHROPIC_API_KEY }}`."
          },
          {
            "id": "yaml",
            "text": "Прямо в файле workflow."
          },
          {
            "id": "env-file",
            "text": "В закоммиченном рядом `.env`."
          }
        ]
      },
      {
        "id": "review-every-pr",
        "prompt": "Нужно, чтобы агент ревьюил каждый новый PR без упоминаний. Что для этого нужно?",
        "options": [
          {
            "id": "prompt-input",
            "text": "Автоматический режим: workflow на событие PR с входом `prompt`."
          },
          {
            "id": "mention",
            "text": "Каждый раз писать `@claude` в PR."
          },
          {
            "id": "local",
            "text": "Запускать `/code-review` локально перед каждым пушем."
          }
        ]
      },
      {
        "id": "headless-limits",
        "prompt": "Вы запускаете `claude -p` в CI, чтобы искать проблемы в коде. Что стоит ограничить?",
        "multiple": true,
        "options": [
          {
            "id": "tools",
            "text": "Инструменты: `--allowedTools` только на чтение."
          },
          {
            "id": "turns",
            "text": "Число ходов: `--max-turns`."
          },
          {
            "id": "output",
            "text": "Формат вывода: только текст."
          },
          {
            "id": "nothing",
            "text": "Ничего: в CI нет ничего ценного."
          }
        ]
      }
    ]
  }
}$json$::jsonb where step_id = 'agent-ci';
insert into private.guide_checks (step_id, key) values ('agent-ci', $json${
  "api-key": {
    "correct": [
      "secrets"
    ],
    "why": {
      "secrets": "Да. Ключ не попадает ни в код, ни в историю git.",
      "yaml": "Ключ окажется в репозитории и в истории git.",
      "env-file": "Тот же результат: секрет в репозитории."
    }
  },
  "review-every-pr": {
    "correct": [
      "prompt-input"
    ],
    "why": {
      "prompt-input": "Да. С `prompt` агент выполняет заданную работу сам, без `@claude`.",
      "mention": "Это ручной режим — легко забыть.",
      "local": "Полезно, но это не CI: проверка зависит от того, не забудет ли человек."
    }
  },
  "headless-limits": {
    "correct": [
      "tools",
      "turns"
    ],
    "why": {
      "tools": "Да. Для поиска проблем агенту не нужно ничего менять.",
      "turns": "Да. Это страхует от бесконечной работы и лишних затрат.",
      "output": "Формат не про безопасность; JSON даже удобнее разбирать скриптом.",
      "nothing": "В CI есть секреты и доступ к репозиторию — права стоит сужать."
    }
  }
}$json$::jsonb)
on conflict (step_id) do update set key = excluded.key;

commit;
