begin;

-- Generated by `npm run library:content` from content/library/. Edit the sources, not this file.
delete from public.library_items where id not in ('prompt-feature', 'prompt-bug', 'prompt-review', 'settings-permissions', 'claude-md-template', 'scoped-rule', 'context-checklist', 'task-template', 'plan-prompt', 'steps-template', 'diff-checklist', 'security-checklist', 'delegation-checklist', 'hook-settings', 'hook-typecheck', 'verify-skill', 'git-rules', 'claude-workflow', 'reviewer-agent', 'headless-script', 'capstone-notes', 'before-after-template');

insert into public.library_items (id, step_id, position, kind, title, summary) values
  ('prompt-feature', 'install', 0, 'prompt', $txt$Запрос: новая функция$txt$, $txt$Агент изучает проект, задаёт вопросы, согласует план и только потом пишет код с проверками.$txt$),
  ('prompt-bug', 'install', 1, 'prompt', $txt$Запрос: поиск ошибки$txt$, $txt$Воспроизвести, найти первопричину, исправить минимально и закрепить тестом.$txt$),
  ('prompt-review', 'install', 2, 'prompt', $txt$Запрос: ревью кода$txt$, $txt$Ревью без правок: конкретные сценарии сбоя вместо выдуманных замечаний.$txt$),
  ('settings-permissions', 'permissions', 3, 'template', $txt$Правила разрешений проекта$txt$, $txt$Проверки без вопросов, а пуш и чтение секретов — под запретом. Запрет всегда сильнее разрешения.$txt$),
  ('claude-md-template', 'claude-md', 4, 'template', $txt$Шаблон CLAUDE.md$txt$, $txt$Коротко и только то, чего агент не узнает из кода: команды, проверки, неочевидные правила.$txt$),
  ('scoped-rule', 'conventions', 5, 'template', $txt$Правило для части проекта$txt$, $txt$Загружается, только когда агент работает с файлами из `paths`, и не занимает контекст в остальное время.$txt$),
  ('context-checklist', 'clean-context', 6, 'checklist', $txt$Когда чистить контекст$txt$, $txt$Признаки раздутого окна и команда на каждый случай.$txt$),
  ('task-template', 'task-anatomy', 7, 'prompt', $txt$Задача с критерием готовности$txt$, $txt$Цель, границы и проверка — три части, без которых агент додумывает сам.$txt$),
  ('plan-prompt', 'plan-first', 8, 'prompt', $txt$Сначала план$txt$, $txt$Для режима планирования: исследование и план без единой правки до вашего согласия.$txt$),
  ('steps-template', 'decomposition', 9, 'template', $txt$План по шагам$txt$, $txt$Каждый шаг проверяемый, небольшой и оставляет проект рабочим.$txt$),
  ('diff-checklist', 'read-diff', 10, 'checklist', $txt$Ревью diff агента$txt$, $txt$Порядок чтения: от самых дешёвых находок к логике, стиль — последним.$txt$),
  ('security-checklist', 'security-deps', 11, 'checklist', $txt$Безопасность в diff$txt$, $txt$Что проверить перед слиянием, даже если тесты зелёные.$txt$),
  ('delegation-checklist', 'delegation-limit', 12, 'checklist', $txt$Отдать агенту или написать самому$txt$, $txt$Быстрая проверка перед тем, как поручить задачу.$txt$),
  ('hook-settings', 'hooks', 13, 'template', $txt$Хук после каждой правки$txt$, $txt$Событие `PostToolUse` с фильтром `Edit|Write` запускает проверку после каждой правки файла.$txt$),
  ('hook-typecheck', 'hooks', 14, 'template', $txt$Скрипт хука: проверка типов$txt$, $txt$Код выхода 2 возвращает ошибки агенту, и он чинит их сразу, пока помнит правку.$txt$),
  ('verify-skill', 'commands-skills', 15, 'template', $txt$Skill «verify»$txt$, $txt$Проверки проекта одной командой `/verify`; агент вызывает её и сам — по `description`.$txt$),
  ('git-rules', 'git-flow', 16, 'template', $txt$Правила Git для агента$txt$, $txt$Ветки, коммиты и PR по правилам проекта; пуш и слияние остаются за человеком.$txt$),
  ('claude-workflow', 'agent-ci', 17, 'template', $txt$Агент в GitHub Actions$txt$, $txt$Отвечает на `@claude` в комментариях. Ключ — только в секретах репозитория.$txt$),
  ('reviewer-agent', 'subagents', 18, 'template', $txt$Субагент-ревьюер$txt$, $txt$Свежий взгляд на diff в своём окне, только с правом чтения.$txt$),
  ('headless-script', 'agent-sdk', 19, 'template', $txt$Скрипт с `claude -p`$txt$, $txt$Агент без интерактива, только с чтением; результат и стоимость — из JSON.$txt$),
  ('capstone-notes', 'idea-to-pr', 20, 'template', $txt$Заметки выпускной задачи$txt$, $txt$Ход работы по всему маршруту и где вы вмешались — материал для «Было / Стало».$txt$),
  ('before-after-template', 'before-after', 21, 'template', $txt$Было / Стало$txt$, $txt$Сравнение на фактах: время, ручные правки, ошибки до слияния, граница делегирования.$txt$)
on conflict (id) do update set step_id = excluded.step_id, position = excluded.position, kind = excluded.kind, title = excluded.title, summary = excluded.summary;

insert into public.library_bodies (item_id, file, body) values
  ('prompt-feature', null, $txt$Ты — мой помощник по разработке. Сначала изучи структуру проекта и существующие соглашения. Помоги реализовать [опишите функцию].

1. Задай вопросы, если требований недостаточно.
2. Предложи короткий план и дождись моего согласования.
3. Реализуй решение небольшими, понятными изменениями.
4. Добавь проверки для важных сценариев и запусти их.
5. Покажи результат, риски и то, что нужно проверить мне.

Не добавляй новые зависимости без необходимости. Не публикуй изменения без моего подтверждения.$txt$),
  ('prompt-bug', null, $txt$Помоги найти и исправить ошибку: [опишите проблему и шаги воспроизведения].

1. Изучи связанный код и воспроизведи проблему.
2. Найди первопричину, объясни её и предложи минимальное исправление.
3. После согласования внеси изменения.
4. Добавь проверку, воспроизводящую ошибку, и убедись, что она проходит после исправления.
5. Покажи изменения и оставшиеся ограничения.

Не меняй несвязанный код и не публикуй изменения без моего подтверждения.$txt$),
  ('prompt-review', null, $txt$Проведи ревью текущих изменений. Пока не редактируй файлы.

1. Изучи контекст и назначение изменённого кода.
2. Проверь корректность, крайние случаи и обработку ошибок.
3. Обрати внимание на безопасность и отсутствующие важные тесты.
4. Для каждой найденной проблемы укажи файл, причину и конкретный сценарий сбоя.
5. Отдели существенные проблемы от необязательных улучшений.

Если серьёзных проблем нет, скажи об этом прямо. Не выдумывай замечания.$txt$),
  ('settings-permissions', $txt$.claude/settings.json$txt$, $txt${
  "permissions": {
    "allow": [
      "Bash(npm run test *)",
      "Bash(npm run lint)",
      "Bash(git diff *)"
    ],
    "deny": [
      "Bash(git push *)",
      "Read(./.env)",
      "Read(./secrets/**)"
    ]
  }
}$txt$),
  ('claude-md-template', $txt$CLAUDE.md$txt$, $txt$# [Название проекта]

[Стек в одну строку: язык, фреймворк, база, как запускается.]

## Команды
- Запуск: `[команда]`
- Проверки перед коммитом: `[линтер] && [тесты]`
- Долгие проверки — только по просьбе: `[команда]`

## Правила
- [Неочевидное правило, которое агент нарушит без подсказки]
- [Что нельзя трогать: сгенерированные файлы, старые миграции]
- Подробно про [тему]: @docs/[файл].md$txt$),
  ('scoped-rule', $txt$.claude/rules/billing.md$txt$, $txt$---
paths:
  - "src/billing/**"
---

# Платежи

- Суммы — в копейках (integer), никогда не float.
- Каждое списание идемпотентно: повторный вызов с тем же ключом ничего не меняет.
- После правок здесь: `npm run test -- billing`.$txt$),
  ('context-checklist', $txt$docs/context-checklist.md$txt$, $txt$# Чистый контекст

- [ ] Новая задача, не связанная с прошлой → `/clear`
- [ ] Нужна нить разговора, но окно разрослось → `/compact сохрани [что важно]`
- [ ] Неудачная ветка разговора → `/rewind` и «сжать отсюда»
- [ ] Короткий вопрос в сторону → `/btw`
- [ ] Агент дважды исправил одно и то же → `/clear` и запрос заново, с тем, что вы узнали
- [ ] Большое исследование → субагент, чтобы выводы пришли без прочитанных файлов$txt$),
  ('task-template', null, $txt$Задача: [что должно получиться, для кого].

Материалы: [файлы, образец в проекте, ссылка на спецификацию].

Границы:
- менять только [папки или модули];
- без новых зависимостей;
- [ограничения, которые видны только вам: нагрузка, внешние потребители].

Готово, когда: [тест, команда или сценарий, которые это подтвердят].

Если чего-то не хватает — сначала спроси.$txt$),
  ('plan-prompt', null, $txt$Изучи, как сейчас устроено [что меняем], и предложи план. Код пока не меняй.

В плане:
- какие файлы изменятся и почему;
- шаги, каждый с проверкой;
- риски и что может сломаться рядом;
- вопросы ко мне, если требования неясны.$txt$),
  ('steps-template', $txt$docs/plan.md$txt$, $txt$# План: [задача]

1. [Шаг] — проверка: `[команда или тест]`
2. [Шаг] — проверка: `[команда или тест]`
3. [Шаг] — проверка: `[команда или тест]`

После каждого шага: тесты зелёные, diff читается за пару минут, можно коммитить.$txt$),
  ('diff-checklist', $txt$docs/review-checklist.md$txt$, $txt$# Ревью diff

- [ ] Список файлов: нет ли лишних
- [ ] Тесты: что проверяют, не ослаблены ли и не удалены ли старые
- [ ] Публичные границы: API, схемы данных, конфиги, зависимости
- [ ] Логика: крайние случаи, обработка ошибок, конкурентный доступ
- [ ] Стиль — последним: его ловят линтер и форматтер
- [ ] Большой diff — ещё и ревьюер в чистом контексте (`/code-review`)$txt$),
  ('security-checklist', $txt$docs/security-checklist.md$txt$, $txt$# Безопасность

- [ ] Ввод пользователя не попадает в SQL, команды или HTML без обработки
- [ ] Права: проверяется, что пользователь вправе сделать действие, а не только что он вошёл
- [ ] Нет ключей, токенов и паролей в коде и логах
- [ ] У каждой новой зависимости есть причина
- [ ] Чтение секретов запрещено в `.claude/settings.json`$txt$),
  ('delegation-checklist', $txt$docs/delegation-checklist.md$txt$, $txt$# Граница делегирования

Отдать агенту, если:
- [ ] есть проверка: тесты, сборка или скриншот скажут «готово» без вас
- [ ] задача типовая: в проекте есть образец
- [ ] ошибка дешёвая и обратимая

Делать самому (агент — исследователь и ревьюер), если:
- [ ] неясен сам замысел
- [ ] ошибка дорогая, а проверить трудно: деньги, права, миграции данных
- [ ] правка на одну строку, которую вы уже видите
- [ ] цель — научиться самому$txt$),
  ('hook-settings', $txt$.claude/settings.json$txt$, $txt${
  "hooks": {
    "PostToolUse": [
      {
        "matcher": "Edit|Write",
        "hooks": [
          {
            "type": "command",
            "command": "node \"$CLAUDE_PROJECT_DIR/.claude/hooks/typecheck.mjs\""
          }
        ]
      }
    ]
  }
}$txt$),
  ('hook-typecheck', $txt$.claude/hooks/typecheck.mjs$txt$, $txt$import { spawnSync } from 'node:child_process';

let input = '';
for await (const chunk of process.stdin) input += chunk;
const { file_path } = JSON.parse(input).tool_input;
if (!/\.tsx?$/.test(file_path)) process.exit(0);

const { status, stdout } = spawnSync('npx tsc --noEmit', { shell: true, encoding: 'utf8' });
if (status !== 0) {
  process.stderr.write(`Ошибки типов после правки ${file_path}:\n${stdout}`);
  process.exit(2);
}$txt$),
  ('verify-skill', $txt$.claude/skills/verify/SKILL.md$txt$, $txt$---
name: verify
description: Проверки проекта перед отчётом о готовности — линтер, сборка, тесты. Используй перед тем, как сказать «готово».
---

Запусти по порядку, остановись на первой ошибке и исправь её:

1. `npm run lint` — 0 ошибок.
2. `npm run build` — вместе с проверкой типов.
3. `npm test` — только затронутые области.$txt$),
  ('git-rules', $txt$CLAUDE.md$txt$, $txt$## Git
- Ветки: `fix/…`, `feat/…` от `main`
- Коммиты: `тип: что сделано`, по-английски, в повелительном наклонении
- PR: проблема, решение, как проверено; скриншоты для изменений UI
- Не пушить и не сливать — это делает человек$txt$),
  ('claude-workflow', $txt$.github/workflows/claude.yml$txt$, $txt$name: Claude Code
on:
  issue_comment:
    types: [created]
jobs:
  claude:
    if: contains(github.event.comment.body, '@claude')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}$txt$),
  ('reviewer-agent', $txt$.claude/agents/reviewer.md$txt$, $txt$---
name: reviewer
description: Свежим взглядом проверяет diff перед коммитом. Используй после крупных правок.
tools: Read, Glob, Grep
model: sonnet
---

Ты ревьюер. Прочитай изменения и найди ошибки корректности,
ослабленные тесты и нарушения требований задачи.
Отмечай только то, что ломает поведение. Стиль не трогай.$txt$),
  ('headless-script', $txt$scripts/triage.sh$txt$, $txt$#!/usr/bin/env bash
# Разбор лога агентом: только чтение, результат и стоимость из JSON.
set -euo pipefail

claude -p "Разбери этот лог и назови причину ошибки" \
  --output-format json \
  --allowedTools "Read,Grep,Glob" \
  < "${1:-logs/today.log}" \
  | jq -r '.result, "Стоимость: \(.total_cost_usd) $"'$txt$),
  ('capstone-notes', $txt$docs/capstone.md$txt$, $txt$# Выпускная задача

Задача:
Критерий готовности:

## Ход работы
- [ ] исследование (субагент)
- [ ] план согласован
- [ ] шаги с проверками
- [ ] ревью в чистом контексте
- [ ] PR и зелёный CI

## Где я вмешался
- 

## Что агент сделал без меня
- $txt$),
  ('before-after-template', $txt$docs/before-after.md$txt$, $txt$# Было / Стало

| | Было | Стало |
|---|---|---|
| Задача | | |
| Время до PR | | |
| Правок руками | | |
| Ошибки до слияния | | |

## Что отдаю агенту целиком
- 

## Что оставляю себе и почему
- $txt$)
on conflict (item_id) do update set file = excluded.file, body = excluded.body;

commit;
